# Generated by Django 3.1.3 on 2021-06-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapit_postcodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsulrow',
            name='postcode',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
